spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueblog2?useUnicode=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: dyf625
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081